-- SQL Setup Script for DiginixIT Supabase Integration
-- Paste these commands into your Supabase SQL Editor (Dashboard > SQL Editor > New query)

-- 1. DROP EXISTING TABLES (If any exist, to start clean)
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.blogs CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.stats CASCADE;

-- 2. CREATE TABLES

-- Settings Table (Global Config using a Key-Value design)
CREATE TABLE public.settings (
    key_name TEXT PRIMARY KEY,
    value_text TEXT NOT NULL
);

-- Blogs Table (Insights Articles)
CREATE TABLE public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    category TEXT NOT NULL DEFAULT 'Tech',
    image TEXT NOT NULL
);

-- Users Table (Custom Registered Users - Client profiles)
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    plan TEXT NOT NULL DEFAULT 'Community',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'Active'
);

-- Stats Table (Platform Dashboard Metrics)
CREATE TABLE public.stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revenue TEXT NOT NULL,
    activeUsers TEXT NOT NULL,
    executions TEXT NOT NULL,
    revenueHistory TEXT NOT NULL,
    visits BIGINT DEFAULT 0
);

-- 3. SEED INITIAL VALUES

-- Seed settings (Includes all site configuration parameters: name, email, phone, and socials)
INSERT INTO public.settings (key_name, value_text) VALUES 
('siteName', 'DIGINIXIT.'),
('contactEmail', 'contact@diginix.com'),
('contactPhone', '+92 300 7960300'),
('maintenanceMode', 'false'),
('linkedin', 'https://linkedin.com/'),
('instagram', 'https://instagram.com/'),
('twitter', 'https://twitter.com/')
ON CONFLICT (key_name) DO UPDATE SET value_text = EXCLUDED.value_text;

-- Seed stats
INSERT INTO public.stats (revenue, activeUsers, executions, revenueHistory, visits) VALUES 
('$0', '0', '0', '0,0,0,0,0,0', 0);

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stats ENABLE ROW LEVEL SECURITY;

-- Settings policies: Everyone can read, authenticated admins can manage
CREATE POLICY "Allow public read on settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on settings" ON public.settings FOR ALL TO authenticated USING (true);

-- Blogs policies: Everyone can read, authenticated admins can manage
CREATE POLICY "Allow public read on blogs" ON public.blogs FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on blogs" ON public.blogs FOR ALL TO authenticated USING (true);

-- Stats policies: Everyone can read, authenticated admins can manage
CREATE POLICY "Allow public read on stats" ON public.stats FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on stats" ON public.stats FOR ALL TO authenticated USING (true);

-- Users policies: Direct access policies for registration, login and profile updates
CREATE POLICY "Allow select on users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow insert on users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update on users" ON public.users FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete on users" ON public.users FOR DELETE TO authenticated USING (true);

-- 5. FUNCTION TO INCREMENT VISITS
-- Secure function to allow public/anon users to increment page visits
CREATE OR REPLACE FUNCTION public.increment_visits()
RETURNS void AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.stats) THEN
        UPDATE public.stats
        SET visits = COALESCE(visits, 0) + 1;
    ELSE
        INSERT INTO public.stats (revenue, activeUsers, executions, revenueHistory, visits)
        VALUES ('$0', '0', '0', '0,0,0,0,0,0', 1);
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execution to anon and authenticated roles
GRANT EXECUTE ON FUNCTION public.increment_visits() TO anon, authenticated;
